# Generated by Django 3.0.5 on 2020-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdetails',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('phone_no', models.BigIntegerField()),
                ('address1', models.CharField(max_length=100)),
                ('paymode', models.CharField(choices=[('Debit_card', 'Debit_card'), ('Credit_card', 'Credit_card')], max_length=30)),
                ('cc_name', models.CharField(max_length=10)),
                ('cc_number', models.IntegerField()),
                ('cc_experation', models.CharField(max_length=20)),
                ('cc_cvv', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
